[package]
name = "chunkmap"
version = "0.1.0"
edition = "2021"

[dependencies]
anvil-region = { path = "../anvil-region" }
image = "0.25.6"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[lib]
name = "chunkmap"
path = "src/lib.rs"
